(source gnu)
(source melpa)

;; base
(depends-on "ivy")
(depends-on "counsel")
(depends-on "evil")
(depends-on "which-key")
(depends-on "projectile")

;; visual enhancements
(depends-on "telephone-line")
(depends-on "afternoon-theme")

;; productivity
(depends-on "autopair")
(depends-on "zoom")
(depends-on "company")
(depends-on "ag")
(depends-on "racer")

;; vcs
(depends-on "magit")

;; modes
(depends-on "cask-mode")
(depends-on "rust-mode")
(depends-on "nix-mode")
(depends-on "markdown-mode")
(depends-on "slime")

;; evil plugins
(depends-on "evil-leader")
(depends-on "evil-magit")

;; projectile plugins
(depends-on "counsel-projectile")
